Глуздов - Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice-python pull request #108
Opened 2020-11-12 17:06 UTC by adgluzdov

2020-11-12 17:07 UTC, adgluzdov commented
@nikitavaneev
@pavelbar

2020-11-12 17:07 UTC, adgluzdov commented
👍

2020-11-12 17:08 UTC, nikitavaneev commented
👍

2020-11-12 20:03 UTC, pavelbar commented
👍

2020-12-04 22:17 UTC, sawirani requested changes

2020-12-04 22:17 UTC, sawirani commented on code/big_integer/src/big_integer.py
> +        self.digits = [0 for i in range(self.SIZE)]
What happens if we pass a string instead of an array ? Please add a check for incorrect data.

2020-12-08 19:27 UTC, merged