Шутина - Лабораторные работы #0, #1
UNN-ITMM-Software/agile-course-practice-python pull request #111
Opened 2020-11-12 18:22 UTC by ShutinaSvetlana

2020-11-13 08:28 UTC, ShutinaSvetlana commented
@GerasimovDG

2020-11-13 08:33 UTC, SylaiseElvenan commented
👍

2020-11-13 08:59 UTC, GerasimovDG commented
👍

2020-12-02 06:17 UTC, sawirani requested changes

2020-12-02 06:17 UTC, sawirani commented on code/ShutinaSvetlana/batcher.py
> +        self.arr = arr
What will happen if we will not give the correct data? Please add tests for this.

2020-12-04 22:18 UTC, sawirani approved these changes

2020-12-04 22:20 UTC, merged