Генералов Александр - Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice-python pull request #112
Opened 2020-11-12 18:48 UTC by AleksandrGeneralov

2020-11-12 19:43 UTC, AleksandrGeneralov commented
@SemenDoc
@kkonsw

2020-11-14 10:45 UTC, kkonsw requested changes

2020-11-14 10:45 UTC, kkonsw commented on code/vector_3d/vector_3d.py
> +        return self.x == x and self.y == y and self.z == z
Use small value to compare floats:
```python
epsilon = 0.000001
return abs(a - b) <= epsilon
```
Python 3.5 adds the `math.isclose()` and `cmath.isclose()` functions which tell whether two values are approximately equal or “close” to each other.

2020-11-16 17:46 UTC, kkonsw commented
:+1:

2020-11-18 06:10 UTC, SemenDoc commented
👍

2020-12-08 17:44 UTC, merged