Капкаев - Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice-python pull request #116
Opened 2020-11-12 22:49 UTC by kapkaevn

@VikaSannikova @vzinovie

2020-11-14 16:27 UTC, vzinovie requested changes

2020-11-16 11:21 UTC, VikaSannikova commented
👍

2020-11-16 11:24 UTC, vzinovie commented
👍

2020-11-16 21:45 UTC, vzinovie commented
👍

2020-11-17 21:59 UTC, kapkaevn commented
@kirill-korniakov

2020-12-04 20:37 UTC, merged