Конаков - Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice-python pull request #122
Opened 2020-11-13 15:40 UTC by AKonia

2020-11-13 18:54 UTC, vzinovie requested changes

2020-11-13 18:54 UTC, vzinovie commented on code/priority_queue/model/priority_queue.py
> +        if not type(e) is int:
Use isinstance() to check variable type.

2020-11-13 18:54 UTC, vzinovie commented on code/priority_queue/model/priority_queue.py
> +        if(not(type(otherpq) == PriorityQueue)):
Same

2020-11-13 19:43 UTC, vzinovie commented
👍

2020-11-14 11:58 UTC, AleksandrPanov commented on code/priority_queue/model/priority_queue.py
> +        while(e < self.ha[j] and (j >= 0)):
Круглые скобки необязательны и наверно здесь лишние

2020-11-14 11:59 UTC, AleksandrPanov commented on code/priority_queue/model/priority_queue.py
> +        if(self.arrlen == 0):
Круглые скобки необязательны и наверно здесь лишние

2020-11-14 12:00 UTC, AleksandrPanov commented on code/priority_queue/model/priority_queue.py
> +        if(self.arrlen == 0):
Аналогично во всех остальных местах

2020-11-14 12:05 UTC, AleksandrPanov commented on code/priority_queue/model/priority_queue.py
> +class PriorityQueue():
Приоритетная очередь должна наверно поддерживать приоритеты) Также нужно реализовать хотя бы следующие функции:
extractMin или extractMax — извлечь элемент с наибольшим приоритетом,
https://neerc.ifmo.ru/wiki/index.php?title=%D0%9F%D1%80%D0%B8%D0%BE%D1%80%D0%B8%D1%82%D0%B5%D1%82%D0%BD%D1%8B%D0%B5_%D0%BE%D1%87%D0%B5%D1%80%D0%B5%D0%B4%D0%B8#:~:text=%D0%9F%D1%80%D0%B8%D0%BE%D1%80%D0%B8%D1%82%D0%B5%D1%82%D0%BD%D0%B0%D1%8F%20%D0%BE%D1%87%D0%B5%D1%80%D0%B5%D0%B4%D1%8C%20(%D0%B0%D0%BD%D0%B3%D0%BB.,%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%BC%20%D1%81%20%D0%B1%D0%BE%D0%BB%D0%B5%D0%B5%20%D0%BD%D0%B8%D0%B7%D0%BA%D0%B8%D0%BC%20%D0%BF%D1%80%D0%B8%D0%BE%D1%80%D0%B8%D1%82%D0%B5%D1%82%D0%BE%D0%BC.&text=%D0%9E%D0%B1%D1%8B%D1%87%D0%BD%D0%BE%20%D0%BF%D1%80%D0%B8%D0%BE%D1%80%D0%B8%D1%82%D0%B5%D1%82%D0%BD%D1%8B%D0%B5%20%D0%BE%D1%87%D0%B5%D1%80%D0%B5%D0%B4%D0%B8%20%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D1%83%D1%8E%D1%82%D1%81%D1%8F%20%D1%81%20%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E%20%D0%BA%D1%83%D1%87%20(%D0%B0%D0%BD%D0%B3%D0%BB.

2020-11-14 12:08 UTC, AleksandrPanov commented on code/priority_queue/model/priority_queue.py
> +class PriorityQueue():
Подробнее можно посмотреть здесь:
http://neerc.ifmo.ru/wiki/index.php?title=%D0%9F%D1%80%D0%B8%D0%BE%D1%80%D0%B8%D1%82%D0%B5%D1%82%D0%BD%D1%8B%D0%B5_%D0%BE%D1%87%D0%B5%D1%80%D0%B5%D0%B4%D0%B8

2020-11-14 13:13 UTC, AKonia commented on code/priority_queue/model/priority_queue.py
> +class PriorityQueue():
extractMin = pop, а extractMax спокойно эмулируется тем же pop, если класть значения домноженные на -1, по умолчанию очердь с приоритетом минимума.

2020-11-14 13:36 UTC, AleksandrPanov commented on code/priority_queue/model/priority_queue.py
> +class PriorityQueue():
У вас приоритетной очереди нет приоритетов. У каждого элемента, который добавляется в очередь должен быть некоторый приоритет, в соответствии с которым он занимает определенное место в очереди.

2020-11-14 13:47 UTC, AleksandrPanov commented on code/priority_queue/model/priority_queue.py
> +class PriorityQueue():
Понял, в качестве ключей используются значения. Тогда вопросов больше не имею.

2020-11-14 13:48 UTC, AleksandrPanov commented
👍

2020-11-14 14:30 UTC, AKonia commented
@kirill-korniakov

2020-12-04 20:48 UTC, merged