Дворянчиков- Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice-python pull request #129
Opened 2020-11-17 12:51 UTC by DvorjanchikovEvgeniy

2020-11-17 13:02 UTC, DvorjanchikovEvgeniy commented
@GusevAlexandr

2020-12-06 14:58 UTC, SylaiseElvenan commented
👍

2020-12-07 18:48 UTC, sawirani requested changes

2020-12-07 18:48 UTC, sawirani commented on code/caesar_cipher/model/caesar_cipher.py
> +        self.offset = offset % self.alphabetVolume
What happens if we pass an array as a shift value? Please add tests for incorrect data

2020-12-09 06:07 UTC, AntonGrishin commented
@DvorjanchikovEvgeniy, пожалуйста добавьте ещё 1-2 ревьюверов, чтобы получить 2 апрув.

2020-12-16 07:02 UTC, merged