Тарасов - Лабораторная работа #2
UNN-ITMM-Software/agile-course-practice-python pull request #139
Opened 2020-12-04 09:19 UTC by Olegka35

2020-12-04 09:21 UTC, Olegka35 commented
@DaniilRoman
@KJlaccHoeUM9l

2020-12-07 10:36 UTC, DaniilRoman commented
:+1:

2020-12-07 18:59 UTC, KJlaccHoeUM9l commented
:+1:

2020-12-09 06:21 UTC, AntonGrishin requested changes

2020-12-09 06:21 UTC, AntonGrishin commented on code/harry_potter_store/src/store.py
> +                raise ValueError("Book type %s must be in %s" % (book_type, Store.book_types))
Раз уж вы меняете, то может тогда лучше использовать f-string? (f"book type {book_type}..."

2020-12-09 06:21 UTC, AntonGrishin commented on code/harry_potter_store/viewmodel/test_viewmodel.py
> +class TestFractionCalculatorViewModel(unittest.TestCase):
Название класса не соответствует его содержанию.

2020-12-09 06:41 UTC, Olegka35 commented on code/harry_potter_store/src/store.py
> +                raise ValueError("Book type %s must be in %s" % (book_type, Store.book_types))
Меняем, потому что не работает, а не исключительно ради рефакторинга :)

2020-12-09 06:58 UTC, Olegka35 commented on code/harry_potter_store/src/store.py
> +                raise ValueError("Book type %s must be in %s" % (book_type, Store.book_types))
f-string не понравился CI в 8638782463ea794735f70a5257f006bb3dc1c53b коммите, пришлось откатывать

2020-12-09 06:59 UTC, Olegka35 commented on code/harry_potter_store/viewmodel/test_viewmodel.py
> +class TestFractionCalculatorViewModel(unittest.TestCase):
Спасибо, исправил

2020-12-09 17:40 UTC, AntonGrishin approved these changes

2020-12-09 17:40 UTC, merged