Санникова - Лабораторная работа #2
UNN-ITMM-Software/agile-course-practice-python pull request #143
Opened 2020-12-08 06:47 UTC by VikaSannikova

2020-12-08 11:05 UTC, VikaSannikova commented
@kapkaevn @vzinovie

2020-12-09 06:15 UTC, AntonGrishin requested changes

2020-12-09 06:15 UTC, AntonGrishin commented on code/triangle/model/triangle.py
> -    def get_area(self):  # площадь
Зачем удалять коммент?

2020-12-09 06:15 UTC, AntonGrishin commented on code/triangle/model/triangle.py
> -    def get_perimeter(self):  # периметр
same

2020-12-09 06:15 UTC, AntonGrishin commented on code/triangle/model/triangle.py
> +    def get_circumcircle_radius(self):  # описананя окружность
typo

2020-12-09 06:21 UTC, AntonGrishin commented on code/triangle/viewmodel/tests_for_viewmodel.py
> +class TestFractionCalculatorViewModel(unittest.TestCase):
Название класса не соответствует содержанию

2020-12-09 08:49 UTC, VikaSannikova commented
@AntonGrishin  done

2020-12-09 09:36 UTC, pavelbar commented
👍

2020-12-09 17:41 UTC, AntonGrishin approved these changes

2020-12-09 17:42 UTC, merged