Кузнецов Виктор - Лабораторная работа #2
UNN-ITMM-Software/agile-course-practice-python pull request #145
Opened 2020-12-08 22:04 UTC by just-sparta

@Fulmo @vzinovie  Please review 🙏

2020-12-09 06:26 UTC, AntonGrishin commented on code/debt_expenses/unittests/viewmodel_unittests.py
> +class TestDebtExpensesViewModelClass(unittest.TestCase):
class в названии класса лишнее.

2020-12-09 06:27 UTC, AntonGrishin requested changes

2020-12-09 06:27 UTC, AntonGrishin commented on code/debt_expenses/unittests/viewmodel_unittests.py
> +class TestDebtExpensesViewModelClass(unittest.TestCase):
class в названии класса лишнее.

2020-12-09 06:27 UTC, AntonGrishin commented on code/debt_expenses/unittests/viewmodel_unittests.py
> +class TestEqualAmountsRepaymentViewModelClass(unittest.TestCase):
same

2020-12-09 06:27 UTC, AntonGrishin commented on code/debt_expenses/unittests/viewmodel_unittests.py
> +class TestEqualPaymentsRepaymentViewModelClass(unittest.TestCase):
same

2020-12-11 13:52 UTC, Fulmo requested changes
Please change your format strings to the correct and short format. You don't need to call format() inside format() twice

2020-12-11 13:52 UTC, Fulmo commented on code/debt_expenses/unittests/viewmodel_unittests.py
> +                                                                     format(expenses, '.0f')))
```suggestion
        self.assertEqual(answer, 'Payment: {:.0f} - Expenses: {:.0f}'.format(payment, expenses))
```

2020-12-11 13:52 UTC, Fulmo commented on code/debt_expenses/unittests/viewmodel_unittests.py
> +                                                                     format(expenses, '.0f')))
```suggestion
        self.assertEqual(answer, 'Payment: {:.0f} - Expenses: {:.0f}'.format(payment, expenses))
```

2020-12-11 13:52 UTC, Fulmo commented on code/debt_expenses/unittests/viewmodel_unittests.py
> +                                                                     format(expenses, '.0f')))
```suggestion
        self.assertEqual(answer, 'Payment: {:.0f} - Expenses: {:.0f}'.format(payment, expenses))
```

2020-12-11 13:52 UTC, Fulmo commented on code/debt_expenses/unittests/viewmodel_unittests.py
> +                                                                     format(expenses, '.0f')))
```suggestion
        self.assertEqual(answer, 'Payment: {:.0f} - Expenses: {:.0f}'.format(payment, expenses))
```

2020-12-11 13:52 UTC, Fulmo commented on code/debt_expenses/unittests/viewmodel_unittests.py
> +                                                                     format(expenses, '.0f')))
```suggestion
        self.assertEqual(answer, 'Payment: {:.0f} - Expenses: {:.0f}'.format(payment, expenses))
```

2020-12-11 13:52 UTC, Fulmo commented on code/debt_expenses/unittests/viewmodel_unittests.py
> +                                                                     format(expenses, '.0f')))
```suggestion
        self.assertEqual(answer, 'Payment: {:.0f} - Expenses: {:.0f}'.format(payment, expenses))
```

2020-12-11 13:52 UTC, Fulmo commented on code/debt_expenses/unittests/viewmodel_unittests.py
> +                                                                     format(expenses, '.0f')))
```suggestion
        self.assertEqual(answer, 'Payment: {:.0f} - Expenses: {:.0f}'.format(payment, expenses))
```

2020-12-11 13:52 UTC, Fulmo commented on code/debt_expenses/unittests/viewmodel_unittests.py
> +                                                                     format(expenses, '.0f')))
```suggestion
        self.assertEqual(answer, 'Payment: {:.0f} - Expenses: {:.0f}'.format(payment, expenses))
```

2020-12-11 13:52 UTC, Fulmo commented on code/debt_expenses/view/debt_view.py
> +                                                                 format(expenses, ".0f") if expenses else ''))
```suggestion
        self.res.config(text='Payment: {:.0f} - Expenses: {:.0f}'.format(payment if payment else '',
                                                                                              expenses if expenses else ''))
```

2020-12-11 14:07 UTC, Fulmo commented
👍🏻 +1

2020-12-16 06:39 UTC, AntonGrishin approved these changes

2020-12-16 06:44 UTC, merged