Камелина - Лабораторная работа #2
UNN-ITMM-Software/agile-course-practice-python pull request #147
Opened 2020-12-09 06:09 UTC by JuliaKamelina

@AnastasiaaSenina @UsovaMA please review

2020-12-09 20:28 UTC, UsovaMA commented on code/float_vector_metrics/viewmodel/test_viewmodel.py
> +    def setUp(self):
Start a test title with "test_"

2020-12-09 20:28 UTC, UsovaMA commented on code/float_vector_metrics/view/view.py
> +    default_sticky = tk.W + tk.E + tk.N + tk.S
Unused variable

2020-12-10 06:27 UTC, JuliaKamelina commented on code/float_vector_metrics/view/view.py
> +    default_sticky = tk.W + tk.E + tk.N + tk.S
Done

2020-12-10 09:21 UTC, UsovaMA commented
:+1:

2020-12-10 11:49 UTC, UsovaMA approved these changes

2020-12-12 22:21 UTC, AnastasiaaSenina requested changes
If entered vectors is not correct, for example, [1, a, 2] and [1, 2, 3], the metrics were calculated ( a number was received, but an error message was expected). Please fix it.

2020-12-12 22:26 UTC, JuliaKamelina commented
@AnastasiaaSenina Done

2020-12-12 22:36 UTC, AnastasiaaSenina approved these changes
👍

2020-12-13 12:33 UTC, merged