Генералов Александр - Лабораторная работа #2
UNN-ITMM-Software/agile-course-practice-python pull request #154
Opened 2020-12-10 18:24 UTC by AleksandrGeneralov

2020-12-12 12:37 UTC, AleksandrGeneralov commented
@SemenDoc
@kkonsw

2020-12-13 09:31 UTC, kkonsw requested changes
Размести `View` и `ViewModel` в отдельных папках и исправь пути при импорте модулей.
```
radix_sort
├── __init__.py
├── main.py
├── model
│   ├── __init__.py
│   ├── model.py
│   └── test_model.py
├── view
│   ├── __init__.py
│   └── view.py
└── viewmodel
    ├── __init__.py
    ├── test_viewmodel.py
    └── viewmodel.py
```

2020-12-13 09:31 UTC, kkonsw commented on code/radix_sort/view/gui_view.py
> +from radix_sort.view.view.gui_view_model import RadixSortViewModel
Неправильный путь при импорте модуля. `View` и `ViewModel` должны быть в разных папках.

2020-12-13 09:31 UTC, kkonsw commented on code/radix_sort/view/gui_view_model_test.py
> +from radix_sort.view.gui_view_model import RadixSortViewModel
То же самое

2020-12-13 18:25 UTC, kkonsw approved these changes
:+1:

2020-12-15 15:21 UTC, SemenDoc commented
👍

2020-12-16 06:47 UTC, AntonGrishin approved these changes

2020-12-16 06:47 UTC, merged