Протас - Лабораторная работа #2
UNN-ITMM-Software/agile-course-practice-python pull request #155
Opened 2020-12-10 19:34 UTC by Fulmo

2020-12-10 20:05 UTC, Fulmo commented
@just-sparta @vzinovie Please review 🙏

2020-12-11 13:35 UTC, just-sparta commented
👍

2020-12-16 06:53 UTC, AntonGrishin requested changes
в целом все ок

2020-12-16 06:53 UTC, AntonGrishin commented on code/fibonacci_heap/viewmodel/test_main_viewmodel.py
> +class TestFractionCalculatorViewModel(unittest.TestCase):
Название класса не совпадает с содержанием

2020-12-17 08:00 UTC, AntonGrishin approved these changes

2020-12-17 08:00 UTC, merged