Ванеев - Лабораторная работа #2
UNN-ITMM-Software/agile-course-practice-python pull request #160
Opened 2020-12-11 11:02 UTC by nikitavaneev

@adgluzdov @pavelbar

2020-12-11 11:04 UTC, pavelbar commented
👍

2020-12-11 11:05 UTC, adgluzdov commented
👍

2020-12-16 06:55 UTC, AntonGrishin requested changes

2020-12-16 06:55 UTC, AntonGrishin commented on code/string_calculator/model/string_calculator_test.py
> +        result = strcalc.add("0")
Исходя из названия теста тут проверяется, что добавление новой строки эквивалентно нулевому результату, теперь тест не соответсвует названию.

2020-12-17 21:41 UTC, pavelbar commented
👍

2020-12-18 07:39 UTC, AntonGrishin approved these changes

2020-12-18 07:40 UTC, merged