Левицкий - Лабораторная работа #2
UNN-ITMM-Software/agile-course-practice-python pull request #163
Opened 2020-12-11 19:59 UTC by Trintal

2020-12-11 20:03 UTC, Trintal commented
@GerasimovDG
@l-bat

2020-12-11 20:23 UTC, GerasimovDG commented
👍

2020-12-11 20:32 UTC, l-bat commented
👍

2020-12-11 20:36 UTC, Trintal commented
@kirill-korniakov

2020-12-16 06:50 UTC, AntonGrishin approved these changes

2020-12-16 06:51 UTC, AntonGrishin commented on code/levitsky_ilya_lab1/viewmodel/test_calculating_volume_3d_figures.py
> +class MyTest(unittest.TestCase):
class TestVolumeViewModel

2020-12-16 06:52 UTC, AntonGrishin requested changes
Исправь, пожалуйста, название класса (отметил выше)

2020-12-16 08:56 UTC, Trintal commented
@AntonGrishin Поправил

2020-12-16 09:02 UTC, AntonGrishin requested changes

2020-12-16 09:02 UTC, AntonGrishin commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
не нужный файл идеи, советую заодно добавить .idea в .gitignore

2020-12-17 14:09 UTC, Trintal commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@AntonGrishin убрал

2020-12-22 14:00 UTC, AntonGrishin approved these changes

2020-12-22 14:00 UTC, merged