Add model new tests, view and viewmodel with tests
UNN-ITMM-Software/agile-course-practice-python pull request #166
Opened 2020-12-11 21:14 UTC by senyamac

2020-12-11 21:57 UTC, senyamac commented
@GerasimovDG
@MaksimenkoAN

2020-12-12 06:13 UTC, MaksimenkoAN commented
👍

2020-12-13 07:34 UTC, GerasimovDG commented
👍

2020-12-13 12:47 UTC, senyamac commented
@kirill-korniakov 
@AntonGrishin 
@homksei

2020-12-16 07:01 UTC, AntonGrishin requested changes

2020-12-16 07:01 UTC, AntonGrishin commented on code/stack/viewmodel/tests_stack_viewmodel.py
> +class MyTestCase(unittest.TestCase):
class TestStackViewModel

2020-12-16 08:12 UTC, senyamac commented on code/stack/viewmodel/tests_stack_viewmodel.py
> +class MyTestCase(unittest.TestCase):
Thank you. The name have been edited.

2020-12-16 10:13 UTC, senyamac commented
@AntonGrishin

2020-12-22 06:41 UTC, AntonGrishin approved these changes

2020-12-22 06:46 UTC, merged