Герасимов - Лабораторная работа #3
UNN-ITMM-Software/agile-course-practice-python pull request #188
Opened 2020-12-19 09:20 UTC by GerasimovDG

2020-12-19 09:24 UTC, GerasimovDG commented
@MaksimenkoAN 
@Trintal

2020-12-20 06:46 UTC, MaksimenkoAN commented
👍

2020-12-20 15:32 UTC, Trintal commented
👍

2020-12-22 11:06 UTC, GerasimovDG commented
@kirill-korniakov

2020-12-24 13:35 UTC, AntonGrishin requested changes
Может стоить добавить тестов на логгер для ViewModel?

2020-12-24 15:24 UTC, GerasimovDG commented
@AntonGrishin, готово

2020-12-25 09:10 UTC, AntonGrishin approved these changes

2020-12-25 09:28 UTC, merged