Сеняев - Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice-python pull request #200
Opened 2020-12-21 22:22 UTC by andrewsen13

2020-12-21 22:32 UTC, andrewsen13 commented
@kkonsw @GorozhaninMihail @AleksandrGeneralov @SemenDoc @AntonGrishin please, review

2020-12-22 18:55 UTC, kkonsw requested changes

2020-12-22 18:55 UTC, kkonsw commented on code/interpolation_search/model/interpolation_search.py
> +        self.search = list()
`self.search` вроде нигде не используется

2020-12-22 19:13 UTC, andrewsen13 commented on code/interpolation_search/model/interpolation_search.py
> +        self.search = list()
поправил

2020-12-22 19:31 UTC, kkonsw approved these changes
:+1:

2020-12-22 19:33 UTC, asenyaev commented
@AntonGrishin could you review it?

2020-12-22 19:35 UTC, andrewsen13 commented
@AntonGrishin could you review it?

2020-12-23 06:22 UTC, AntonGrishin approved these changes

2020-12-23 06:28 UTC, merged