Левицкий - Лабораторная работа #3
UNN-ITMM-Software/agile-course-practice-python pull request #201
Opened 2020-12-22 08:54 UTC by Trintal

2020-12-22 09:44 UTC, Trintal commented
@GerasimovDG
@l-bat

2020-12-22 09:45 UTC, GerasimovDG commented
👍

2020-12-22 09:50 UTC, l-bat commented on code/levitsky_ilya_lab1/logger/reallogger.py
> +        logging.basicConfig(filename='../logger/calculate_volume.log', level=logging.INFO)
Please use `os.path.join`

2020-12-22 09:50 UTC, l-bat commented on code/levitsky_ilya_lab1/view/view.py
> +        result_str += ('%s\n' % messages[i])
```suggestion
     result_str = '\n'.join([message  for message in messages])
```

2020-12-22 09:50 UTC, l-bat commented on code/levitsky_ilya_lab1/view/view.py
> +        return "NaN"
It is a equal conditions, isn't it?

2020-12-22 09:55 UTC, l-bat commented
💩

2020-12-22 10:51 UTC, Trintal commented on code/levitsky_ilya_lab1/logger/reallogger.py
> +        logging.basicConfig(filename='../logger/calculate_volume.log', level=logging.INFO)
done

2020-12-22 10:51 UTC, Trintal commented on code/levitsky_ilya_lab1/view/view.py
> +        result_str += ('%s\n' % messages[i])
done

2020-12-22 10:51 UTC, Trintal commented on code/levitsky_ilya_lab1/view/view.py
> +        return "NaN"
done

2020-12-22 11:01 UTC, l-bat commented
Thank you!

2020-12-22 11:01 UTC, l-bat approved these changes
:+1:

2020-12-22 11:02 UTC, Trintal commented
@kirill-korniakov

2020-12-22 14:07 UTC, AntonGrishin requested changes
@Trintal нужно зарезолвить конфликты

2020-12-22 18:51 UTC, Trintal commented
@AntonGrishin  готово

2020-12-24 21:00 UTC, sawirani commented
Добавь тесты на viewModel

2020-12-24 21:01 UTC, sawirani requested changes
Добавь тесты на viewModel

2020-12-25 06:50 UTC, Trintal commented
@sawirani добавил

2020-12-25 09:11 UTC, AntonGrishin approved these changes

2020-12-25 09:13 UTC, sawirani approved these changes

2020-12-25 09:16 UTC, merged