Галочкин - Лабораторная работа #2
UNN-ITMM-Software/agile-course-practice-python pull request #202
Opened 2020-12-22 10:20 UTC by ZextarTFC

@mariamosonova 
@MaksimGer

2020-12-22 10:42 UTC, mariamosonova commented
:+1:

2020-12-22 10:52 UTC, MaksimGer commented
:+1:

2020-12-22 14:09 UTC, AntonGrishin requested changes

2020-12-22 14:09 UTC, AntonGrishin commented on code/galochkin_aleksei_lab_1/viewmodel/viewmodel_test.py
> +class MyTestCase(unittest.TestCase):
Сделай, пожалуйста, говорящее название тест класса

2020-12-22 14:09 UTC, AntonGrishin commented on code/galochkin_aleksei_lab_1/viewmodel/viewmodel_test.py
> +    # def test_clear_output_error(self):
нужно либо удалить мертвый код, либо раскомментировать

2020-12-23 05:59 UTC, ZextarTFC commented on code/galochkin_aleksei_lab_1/viewmodel/viewmodel_test.py
> +    # def test_clear_output_error(self):
Запрошенные изменения сделаны

2020-12-23 06:11 UTC, AntonGrishin approved these changes

2020-12-23 06:16 UTC, merged