Галочкин - Лабораторная работа #3
UNN-ITMM-Software/agile-course-practice-python pull request #231
Opened 2020-12-27 18:25 UTC by ZextarTFC

@mariamosonova 
@MaksimGer

2020-12-28 08:12 UTC, MaksimGer commented
:+1:

2020-12-28 11:41 UTC, mariamosonova commented
:+1:

2020-12-29 07:21 UTC, sawirani requested changes
Добавь тесты на viewModel

2020-12-29 10:10 UTC, sawirani approved these changes

2020-12-29 10:48 UTC, merged