Соколова - Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice-python pull request #66
Opened 2020-11-09 16:17 UTC by mariamosonova

@DaniilRoman
@GerasimovDG

2020-11-09 19:31 UTC, DaniilRoman commented
:+1:

2020-11-09 19:34 UTC, GerasimovDG commented
👍

2020-11-24 05:34 UTC, sawirani requested changes
Please add tests for negative cases

2020-11-24 15:25 UTC, sawirani approved these changes

2020-11-24 17:10 UTC, merged