Кузнецов Виктор - Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice-python pull request #69
Opened 2020-11-09 19:01 UTC by just-sparta

2020-11-09 19:11 UTC, just-sparta commented
Please review )
@kapkaevn @ZinovievVladimir @Fulmo

2020-11-10 19:58 UTC, Fulmo commented
👍🏻

2020-11-12 21:47 UTC, vzinovie requested changes

2020-11-12 21:47 UTC, vzinovie commented on code/kuznetsov_victor_lab1/debt.py
> +            raise ValueError('Values must be positive numbers!')
`positive` or `non-negative`?

2020-11-12 21:47 UTC, vzinovie commented on code/kuznetsov_victor_lab1/debt.py
> +            raise Exception('Year must be less than {}!'.format(self.period))
What about year < 1 ?

2020-11-12 21:47 UTC, vzinovie commented on code/kuznetsov_victor_lab1/debt.py
> +            raise Exception('Year must be less than {}!'.format(self.period))
Same

2020-11-12 21:47 UTC, vzinovie commented on code/kuznetsov_victor_lab1/debt.py
> +        while i < year:
I think `for i in range(year):` will be better here.

2020-11-13 13:24 UTC, vzinovie commented
👍

2020-11-28 16:36 UTC, sawirani approved these changes

2020-11-29 08:53 UTC, sawirani approved these changes

2020-11-29 15:17 UTC, merged