Камелина - Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice-python pull request #84
Opened 2020-11-10 15:30 UTC by JuliaKamelina

@AnastasiaaSenina @UsovaMA please review

2020-11-10 15:48 UTC, AnastasiaaSenina commented on code/statistical_values/model/statistics.py
> +
Please add error description.

2020-11-10 15:54 UTC, AnastasiaaSenina requested changes

2020-11-10 15:54 UTC, AnastasiaaSenina commented on code/statistical_values/model/statistics.py
> +    def __init__(self, values=None):
Please make the class name  and method more descriptive.

2020-11-10 15:54 UTC, AnastasiaaSenina commented on code/statistical_values/model/statistics.py
> +            raise ValueError
Some

2020-11-10 16:00 UTC, UsovaMA commented on code/statistical_values/model/test_statistics.py
> +        self.assertEqual(stat.mean(), 2.0)
Split tests into blocks:
Arrange
Act
Assert

2020-11-10 23:58 UTC, UsovaMA commented
Actually I suggested separating Act from Assert...

2020-11-11 14:34 UTC, UsovaMA commented
:+1:

2020-11-11 17:19 UTC, AnastasiaaSenina approved these changes
👍

2020-11-11 18:57 UTC, JuliaKamelina commented
@kirill-korniakov

2020-11-24 13:18 UTC, sawirani approved these changes

2020-11-24 15:23 UTC, merged